# Generated by Django 5.0.14 on 2025-XX-XX XX:XX

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pigeon_age'),  # Замени на последнюю миграцию
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Добавляем новые поля в Pigeon
        migrations.AddField(
            model_name='pigeon',
            name='listing_type',
            field=models.CharField(
                choices=[('fixed', 'Фиксированная цена'), ('auction', 'Аукцион')],
                default='fixed',
                max_length=10,
                verbose_name='Тип продажи'
            ),
        ),
        migrations.AddField(
            model_name='pigeon',
            name='start_price',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Минимальная ставка для аукциона',
                max_digits=10,
                null=True,
                verbose_name='Начальная цена (для аукциона)'
            ),
        ),
        migrations.AddField(
            model_name='pigeon',
            name='current_price',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Обновляется автоматически при новых ставках',
                max_digits=10,
                null=True,
                verbose_name='Текущая цена'
            ),
        ),
        migrations.AddField(
            model_name='pigeon',
            name='auction_end_date',
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name='Дата окончания аукциона'
            ),
        ),
        migrations.AddField(
            model_name='pigeon',
            name='is_sold',
            field=models.BooleanField(
                default=False,
                verbose_name='Продан'
            ),
        ),
        migrations.AddField(
            model_name='pigeon',
            name='winner',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='won_auctions',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Победитель аукциона'
            ),
        ),
        
        # Создаём модель Bid
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма ставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время ставки')),
                ('pigeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='core.pigeon', verbose_name='Голубь')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_bids', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Ставка',
                'verbose_name_plural': 'Ставки',
                'ordering': ['-amount', '-created_at'],
            },
        ),
    ]
