# Generated by Django 5.0.1 on 2026-01-11 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название клиники или имя ветеринара', max_length=200, verbose_name='Название / Имя')),
                ('photo', models.ImageField(help_text='Фото клиники или врача', upload_to='veterinarians/', verbose_name='Фото')),
                ('description', models.TextField(help_text='Подробное описание предоставляемых услуг', verbose_name='Описание услуг')),
                ('phone', models.CharField(help_text='Контактный номер телефона', max_length=20, verbose_name='Телефон')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Номер WhatsApp', max_length=20, verbose_name='WhatsApp')),
                ('city', models.CharField(choices=[('dushanbe', 'Душанбе'), ('khujand', 'Худжанд'), ('kulob', 'Куляб'), ('qurghonteppa', 'Курган-Тюбе'), ('hisor', 'Гисар'), ('istaravshan', 'Истаравшан'), ('tursunzoda', 'Турсунзаде'), ('khorog', 'Хорог'), ('vahdat', 'Вахдат'), ('panjakent', 'Пенджикент'), ('other', 'Другой город')], default='dushanbe', help_text='Город расположения', max_length=50, verbose_name='Город')),
                ('address', models.CharField(help_text='Полный адрес клиники', max_length=300, verbose_name='Адрес')),
                ('is_vip', models.BooleanField(default=False, help_text='Премиум размещение с выделением', verbose_name='VIP размещение')),
                ('is_approved', models.BooleanField(default=False, help_text='Запись прошла модерацию', verbose_name='Одобрено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Ветеринар / Ветклиника',
                'verbose_name_plural': 'Ветеринары и Ветклиники',
                'ordering': ['-is_vip', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('cat', 'Кошки / Гурбаҳо'), ('dog', 'Собаки / Сагҳо'), ('parrot', 'Попугаи / Тӯтиҳо'), ('canary', 'Канарейки / Қанариҳо'), ('partridge', 'Кеклик / Кабкҳо'), ('chicken', 'Куры и Петухи / Мурғ ва Хурӯс'), ('pigeon', 'Голуби / Кафтарҳо'), ('rabbit', 'Кролики / Харгӯшҳо'), ('horse', 'Лошади / Аспҳо'), ('cow', 'Коровы / Говҳо'), ('goat', 'Козы / Бузҳо'), ('sheep', 'Бараны / Гӯсфандҳо'), ('fish', 'Рыбки / Моҳиҳо')], db_index=True, help_text='Вид животного', max_length=50, verbose_name='Категория')),
                ('title', models.CharField(help_text='Название объявления', max_length=200, verbose_name='Название')),
                ('description', models.TextField(help_text='Подробное описание животного', verbose_name='Описание')),
                ('gender', models.CharField(choices=[('male', 'Самец / Нар'), ('female', 'Самка / Мода'), ('pair', 'Пара / Ҷуфт'), ('unknown', 'Не указано')], default='unknown', help_text='Пол животного', max_length=20, verbose_name='Пол')),
                ('age', models.CharField(blank=True, help_text='Например: 2 года, 6 месяцев, 1.5 года', max_length=100, verbose_name='Возраст')),
                ('breed', models.CharField(blank=True, help_text='Порода животного (если есть)', max_length=100, verbose_name='Порода')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена в сомони (TJS)', max_digits=10, verbose_name='Цена')),
                ('listing_type', models.CharField(choices=[('fixed', 'Фиксированная цена'), ('auction', 'Аукцион')], default='fixed', help_text='Аукцион доступен только для голубей', max_length=10, verbose_name='Тип продажи')),
                ('start_price', models.DecimalField(blank=True, decimal_places=2, help_text='Минимальная ставка для аукциона', max_digits=10, null=True, verbose_name='Начальная цена (для аукциона)')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, help_text='Обновляется автоматически при новых ставках', max_digits=10, null=True, verbose_name='Текущая цена')),
                ('auction_end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания аукциона')),
                ('is_sold', models.BooleanField(default=False, verbose_name='Продан')),
                ('payment_receipt', models.ImageField(blank=True, help_text='Скриншот чека оплаты для аукциона (3 TJS)', null=True, upload_to='receipts/', verbose_name='Чек оплаты')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('main_photo', models.ImageField(help_text='Основное фото животного', upload_to='animals/%Y/%m/', verbose_name='Главное фото')),
                ('video_url', models.URLField(blank=True, help_text='Ссылка на YouTube видео (необязательно)', max_length=500, null=True, verbose_name='Видео (YouTube)')),
                ('city', models.CharField(choices=[('dushanbe', 'Душанбе'), ('khujand', 'Худжанд'), ('kulob', 'Куляб'), ('qurghonteppa', 'Курган-Тюбе'), ('hisor', 'Гисар'), ('istaravshan', 'Истаравшан'), ('tursunzoda', 'Турсунзаде'), ('khorog', 'Хорог'), ('vahdat', 'Вахдат'), ('panjakent', 'Пенджикент'), ('other', 'Другой город')], db_index=True, default='dushanbe', help_text='Город продавца', max_length=50, verbose_name='Город')),
                ('phone', models.CharField(help_text='Контактный номер телефона', max_length=20, verbose_name='Телефон')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Номер WhatsApp (например: +992900123456)', max_length=20, verbose_name='WhatsApp')),
                ('telegram_username', models.CharField(blank=True, help_text='Имя пользователя в Telegram (без @)', max_length=50, verbose_name='Telegram')),
                ('is_vip', models.BooleanField(default=False, help_text='Премиум размещение с золотой рамкой', verbose_name='VIP размещение')),
                ('is_approved', models.BooleanField(default=False, help_text='Объявление прошло модерацию', verbose_name='Одобрено')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Количество просмотров объявления', verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('favorites', models.ManyToManyField(blank=True, help_text='Пользователи, добавившие в избранное', related_name='favorite_animals', to=settings.AUTH_USER_MODEL, verbose_name='В избранном у')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_animal_auctions', to=settings.AUTH_USER_MODEL, verbose_name='Победитель аукциона')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='animals/gallery/%Y/%m/', verbose_name='Фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.animal', verbose_name='Животное')),
            ],
            options={
                'verbose_name': 'Фото животного',
                'verbose_name_plural': 'Галерея фото',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма ставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время ставки')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='core.animal', verbose_name='Животное (голубь)')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_bids', to=settings.AUTH_USER_MODEL, verbose_name='Ставивший')),
            ],
            options={
                'verbose_name': 'Ставка',
                'verbose_name_plural': 'Ставки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.animal', verbose_name='Животное')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='От 1 до 5', verbose_name='Оценка')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Chat ID')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Рейтинг')),
                ('total_sales', models.PositiveIntegerField(default=0, verbose_name='Всего продаж')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['-created_at'], name='core_animal_created_8d7496_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['category', '-created_at'], name='core_animal_categor_e5b2d7_idx'),
        ),
        migrations.AddIndex(
            model_name='animal',
            index=models.Index(fields=['city', 'category'], name='core_animal_city_1d911a_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('seller', 'buyer'), name='no_self_review'),
        ),
    ]
