# Generated by Django 5.0.14 on 2025-12-20 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pigeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название голубя/объявления', max_length=200, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена в сомони (TJS)', max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(help_text='Подробное описание птицы', verbose_name='Описание')),
                ('image', models.ImageField(help_text='Основное фото голубя', upload_to='pigeons/', verbose_name='Фото')),
                ('video_url', models.URLField(blank=True, help_text='Ссылка на YouTube видео (необязательно)', max_length=500, null=True, verbose_name='Видео (YouTube)')),
                ('is_vip', models.BooleanField(default=False, help_text='Премиум размещение с золотой рамкой', verbose_name='VIP размещение')),
                ('phone', models.CharField(help_text='Контактный номер телефона', max_length=20, verbose_name='Телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pigeons', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Голубь',
                'verbose_name_plural': 'Голуби',
                'ordering': ['-is_vip', '-created_at'],
            },
        ),
    ]
