# Generated by Django 5.0.1 on 2026-01-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='category',
            field=models.CharField(choices=[('cat', 'Кошки / Гурбаҳо'), ('dog', 'Собаки / Сагҳо'), ('parrot', 'Попугаи / Тӯтиҳо'), ('canary', 'Канарейки / Қанариҳо'), ('partridge', 'Кеклик / Кабкҳо'), ('chicken', 'Куры и Петухи / Мурғ ва Хурӯс'), ('pigeon', 'Голуби / Кафтарҳо'), ('rabbit', 'Кролики / Харгӯшҳо'), ('horse', 'Лошади / Аспҳо'), ('cow', 'Коровы / Говҳо'), ('goat', 'Козы / Бузҳо'), ('sheep', 'Бараны / Гӯсфандҳо'), ('fish', 'Рыбки / Моҳиҳо'), ('hamster', 'Хомяки / Хомякҳо'), ('turtle', 'Черепахи / Сангпуштҳо'), ('bird_other', 'Другие птицы / Паррандаҳои дигар'), ('reptile', 'Рептилии / Хазанда'), ('other', 'Другие / Дигар')], db_index=True, help_text='Вид животного', max_length=50, verbose_name='Категория'),
        ),
    ]
