# Generated by Django 5.0.14 on 2025-12-20 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pigeon',
            name='breed',
            field=models.CharField(choices=[('lailaki', 'Лайлаки'), ('chinny', 'Чинни'), ('sochi', 'Сочи'), ('tugma', 'Тугма'), ('metis', 'Метис'), ('other', 'Другая')], default='other', help_text='Порода голубя', max_length=50, verbose_name='Порода'),
        ),
        migrations.AddField(
            model_name='pigeon',
            name='game_type',
            field=models.CharField(choices=[('flight', 'Только полет'), ('game', 'Бойные/Игровые'), ('decoration', 'Декоративные')], default='flight', help_text='Назначение голубя', max_length=50, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='pigeon',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Объявление прошло модерацию', verbose_name='Одобрено'),
        ),
        migrations.AddField(
            model_name='pigeon',
            name='sex',
            field=models.CharField(choices=[('male', 'Самец'), ('female', 'Самка'), ('pair', 'Пара')], default='male', help_text='Пол голубя или пара', max_length=20, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='pigeon',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Имя пользователя в Telegram (без @)', max_length=50, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='pigeon',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Номер WhatsApp (например: +992900123456)', max_length=20, verbose_name='WhatsApp'),
        ),
        migrations.AddIndex(
            model_name='pigeon',
            index=models.Index(fields=['is_approved', '-created_at'], name='core_pigeon_is_appr_593798_idx'),
        ),
        migrations.AddIndex(
            model_name='pigeon',
            index=models.Index(fields=['breed', 'sex'], name='core_pigeon_breed_31ad65_idx'),
        ),
    ]
