# Generated by Django 5.0.14 on 2025-12-20 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pigeon_breed_pigeon_game_type_pigeon_is_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pigeon',
            name='favorites',
            field=models.ManyToManyField(blank=True, help_text='Пользователи, добавившие в избранное', related_name='favorite_pigeons', to=settings.AUTH_USER_MODEL, verbose_name='В избранном у'),
        ),
        migrations.AddField(
            model_name='pigeon',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Количество просмотров объявления', verbose_name='Просмотры'),
        ),
    ]
