# Generated by Django 5.0.1 on 2026-01-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_animal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('sold', 'Продано'), ('archived', 'В архиве')], db_index=True, default='active', help_text='Статус объявления', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Синяя галочка - доверенный продавец', verbose_name='Верифицирован'),
        ),
    ]
