# Generated by Django 5.0.1 on 2026-01-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_animal_status_userprofile_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='flight_duration',
            field=models.CharField(blank=True, help_text='Например: 2-3 часа, до 5 часов', max_length=100, null=True, verbose_name='Длительность полета'),
        ),
        migrations.AddField(
            model_name='animal',
            name='game_style',
            field=models.CharField(blank=True, help_text='Например: Столбовой бой, Ленточный', max_length=100, null=True, verbose_name='Стиль игры/бой'),
        ),
        migrations.AddField(
            model_name='animal',
            name='gender_livestock',
            field=models.CharField(blank=True, choices=[('male', 'Самец'), ('female', 'Самка')], help_text='Пол животного', max_length=20, null=True, verbose_name='Пол (скот)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='gender_pigeon',
            field=models.CharField(blank=True, choices=[('male', 'Самец'), ('female', 'Самка'), ('pair', 'Пара')], help_text='Пол голубя или пара', max_length=20, null=True, verbose_name='Пол (голубь)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='has_passport',
            field=models.BooleanField(blank=True, default=False, help_text='Наличие ветеринарного паспорта', null=True, verbose_name='Есть паспорт/прививки'),
        ),
        migrations.AddField(
            model_name='animal',
            name='livestock_breed',
            field=models.CharField(blank=True, help_text='Например: Абердин-ангус, Гиссарская, Ахалтекинская', max_length=100, null=True, verbose_name='Порода скота'),
        ),
        migrations.AddField(
            model_name='animal',
            name='pet_breed',
            field=models.CharField(blank=True, help_text='Например: Британская, Персидская, Немецкая овчарка', max_length=100, null=True, verbose_name='Порода питомца'),
        ),
        migrations.AddField(
            model_name='animal',
            name='pigeon_breed',
            field=models.CharField(blank=True, help_text='Например: Бойный, Статный, Николаевский', max_length=100, null=True, verbose_name='Порода голубя'),
        ),
        migrations.AddField(
            model_name='animal',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Вес животного в килограммах', max_digits=6, null=True, verbose_name='Вес (кг)'),
        ),
    ]
