# Generated by Django 5.0.14 on 2025-12-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pigeon_favorites_pigeon_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pigeon',
            name='city',
            field=models.CharField(choices=[('dushanbe', 'Душанбе'), ('khujand', 'Худжанд'), ('kulob', 'Куляб'), ('qurghonteppa', 'Курган-Тюбе'), ('hisor', 'Гисар'), ('istaravshan', 'Истаравшан'), ('tursunzoda', 'Турсунзаде'), ('khorog', 'Хорог'), ('vahdat', 'Вахдат'), ('panjakent', 'Пенджикент'), ('other', 'Другой город')], default='dushanbe', help_text='Город продавца', max_length=50, verbose_name='Город'),
        ),
    ]
