# Generated by Django 5.0.1 on 2026-01-11 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_animal_flight_duration_animal_game_style_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='route_from',
            field=models.CharField(blank=True, help_text='Откуда можно забрать животное', max_length=100, null=True, verbose_name='Откуда'),
        ),
        migrations.AddField(
            model_name='animal',
            name='route_to',
            field=models.CharField(blank=True, help_text='Куда доставляется животное', max_length=100, null=True, verbose_name='Куда'),
        ),
        migrations.AddField(
            model_name='animal',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('sprinter', 'Спринтер'), ('porter', 'Портер'), ('sedan', 'Легковая'), ('minivan', 'Минивэн')], help_text='Тип транспорта для перевозки', max_length=50, null=True, verbose_name='Тип авто'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='category',
            field=models.CharField(choices=[('cat', 'Кошки / Гурбаҳо'), ('dog', 'Собаки / Сагҳо'), ('parrot', 'Попугаи / Тӯтиҳо'), ('canary', 'Канарейки / Қанариҳо'), ('partridge', 'Кеклик / Кабкҳо'), ('chicken', 'Куры и Петухи / Мурғ ва Хурӯс'), ('pigeon', 'Голуби / Кафтарҳо'), ('rabbit', 'Кролики / Харгӯшҳо'), ('horse', 'Лошади / Аспҳо'), ('cow', 'Коровы / Говҳо'), ('goat', 'Козы / Бузҳо'), ('sheep', 'Бараны / Гӯсфандҳо'), ('fish', 'Рыбки / Моҳиҳо'), ('hamster', 'Хомяки / Хомякҳо'), ('turtle', 'Черепахи / Сангпуштҳо'), ('bird_other', 'Другие птицы / Паррандаҳои дигар'), ('reptile', 'Рептилии / Хазанда'), ('transport', 'Зоо-Такси / Ташвиқот'), ('other', 'Другие / Дигар')], db_index=True, help_text='Вид животного', max_length=50, verbose_name='Категория'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Предложенная цена')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('message', models.TextField(blank=True, help_text='Опциональное сообщение от покупателя', verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата предложения')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.animal', verbose_name='Животное')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_offers', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Предложение цены',
                'verbose_name_plural': 'Предложения цен',
                'ordering': ['-created_at'],
            },
        ),
    ]
