# Generated by Django 5.0.14 on 2025-12-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pigeon_auction_end_date_pigeon_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pigeon',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Оплата подтверждена администратором', verbose_name='Оплачено'),
        ),
        migrations.AddField(
            model_name='pigeon',
            name='payment_receipt',
            field=models.ImageField(blank=True, help_text='Скриншот чека оплаты для аукциона (3 TJS)', null=True, upload_to='receipts/', verbose_name='Чек оплаты'),
        ),
    ]
