# Generated by Django 5.0.1 on 2026-01-26 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_animal_route_from_animal_route_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Баланс внутреннего кошелька в сомони (TJS)', max_digits=10, verbose_name='Баланс кошелька'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Самец / Нар'), ('female', 'Самка / Мода'), ('pair', 'Пара / Ҷуфт'), ('unknown', 'Не указано')], default='unknown', help_text='Пол животного', max_length=20, verbose_name='Пол'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('transaction_type', models.CharField(choices=[('add', 'Пополнение'), ('deduct', 'Списание'), ('payment', 'Платеж'), ('refund', 'Возврат')], max_length=20, verbose_name='Тип транзакции')),
                ('description', models.CharField(blank=True, help_text='Краткое описание причины транзакции', max_length=255, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_transa_user_id_1afe97_idx')],
            },
        ),
    ]
