# Generated by Django 5.0.1 on 2026-03-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_balance_alter_animal_gender_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='color_variety',
            field=models.CharField(blank=True, help_text='Например: рыжий, чёрно-белый, сизый', max_length=100, null=True, verbose_name='Расцветка / Масть'),
        ),
        migrations.AddField(
            model_name='animal',
            name='health_status',
            field=models.CharField(blank=True, choices=[('healthy', 'Здоров'), ('vaccinated', 'Вакцинирован'), ('with_passport', 'Есть паспорт'), ('unknown', 'Не указано')], default='unknown', help_text='Состояние здоровья животного', max_length=30, null=True, verbose_name='Статус здоровья'),
        ),
    ]
