# Generated by Django 5.0.1 on 2026-03-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_color_health_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_negotiable',
            field=models.BooleanField(default=False, help_text='Отметьте, если цена обсуждается', verbose_name='Цена договорная'),
        ),
    ]
