# Generated by Django 5.0.14 on 2025-12-24 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '⭐ 1 - Очень плохо'), (2, '⭐⭐ 2 - Плохо'), (3, '⭐⭐⭐ 3 - Нормально'), (4, '⭐⭐⭐⭐ 4 - Хорошо'), (5, '⭐⭐⭐⭐⭐ 5 - Отлично')], verbose_name='Оценка')),
                ('text', models.TextField(blank=True, help_text='Опишите ваш опыт покупки', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrote_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Автор отзыва')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(('seller', models.F('author')), _negated=True), name='no_self_review'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('seller', 'author')},
        ),
    ]
