# Generated by Django 5.0.1 on 2026-03-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_is_negotiable'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='available_days',
            field=models.CharField(blank=True, help_text='Например: Ежедневно, Пн-Пт, По заявке', max_length=100, null=True, verbose_name='Дни работы'),
        ),
        migrations.AddField(
            model_name='animal',
            name='cargo_capacity',
            field=models.CharField(blank=True, help_text='Например: куры до 50 шт, собаки 2-3 головы, любые животные', max_length=200, null=True, verbose_name='Вместимость / Тип груза'),
        ),
        migrations.AddField(
            model_name='animal',
            name='departure_time',
            field=models.CharField(blank=True, help_text='Например: 08:00, 14:00, 18:00', max_length=100, null=True, verbose_name='Время отправления'),
        ),
    ]
