# Generated by Django 5.0.14 on 2025-12-25 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_review_review_no_self_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigeon',
            name='breed',
            field=models.CharField(choices=[('lailaki', 'Лайлаки'), ('sochi', 'Сочи'), ('chinny', 'Чинны'), ('sych', 'Сыч'), ('zhuk', 'Жук'), ('mallya', 'Малля'), ('kukcha', 'Кукча'), ('tajik_highflyer', 'Таджикский Лётный'), ('two_crested', 'Двухчубый'), ('tugma', 'Тугма'), ('metis', 'Метис'), ('other', 'Другая')], default='other', help_text='Порода голубя', max_length=50, verbose_name='Порода'),
        ),
        migrations.CreateModel(
            name='PigeonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pigeon_images/', verbose_name='Изображение')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Порядок отображения изображения (0 = первое)', verbose_name='Порядок')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('pigeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.pigeon', verbose_name='Голубь')),
            ],
            options={
                'verbose_name': 'Изображение голубя',
                'verbose_name_plural': 'Изображения голубей',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
