# Generated by Django 5.0.1 on 2025-12-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_pigeon_breed_pigeonimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название (RU)')),
                ('title_tj', models.CharField(max_length=255, verbose_name='Название (TJ)')),
                ('description_ru', models.TextField(help_text='Краткое описание заболевания', verbose_name='Описание (RU)')),
                ('description_tj', models.TextField(help_text='Краткое описание заболевания', verbose_name='Описание (TJ)')),
                ('symptoms_ru', models.TextField(help_text='Описание симптомов заболевания', verbose_name='Симптомы (RU)')),
                ('symptoms_tj', models.TextField(help_text='Описание симптомов заболевания', verbose_name='Симптомы (TJ)')),
                ('treatment_ru', models.TextField(help_text='Методы и рекомендации по лечению', verbose_name='Лечение (RU)')),
                ('treatment_tj', models.TextField(help_text='Методы и рекомендации по лечению', verbose_name='Лечение (TJ)')),
                ('image', models.ImageField(help_text='Главное изображение для статьи', upload_to='health_guides/', verbose_name='Изображение')),
                ('youtube_url', models.URLField(blank=True, help_text='Ссылка на видео (например: https://www.youtube.com/watch?v=VIDEO_ID)', max_length=500, null=True, verbose_name='YouTube видео')),
                ('slug', models.SlugField(help_text='Будет создан автоматически из названия', max_length=255, unique=True, verbose_name='URL slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Статья о здоровье',
                'verbose_name_plural': 'Энциклопедия лечения',
                'ordering': ['-created_at'],
            },
        ),
    ]
